package com.coderslab.entity;
// Generated Sep 17, 2017 10:39:16 AM by Hibernate Tools 4.3.1

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Users generated by hbm2java
 */
@Entity
public class Users implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    private String name;
    private String gender;
    private String country;
    private String aboutYou;
    private boolean mailingList;

    public Users() {
    }

    public Users(Integer id, String name, String gender, String country, String aboutYou, boolean mailingList) {
        this.id = id;
        this.name = name;
        this.gender = gender;
        this.country = country;
        this.aboutYou = aboutYou;
        this.mailingList = mailingList;
    }

    public Users(String name, String gender, String country, String aboutYou, boolean mailingList) {
        this.name = name;
        this.gender = gender;
        this.country = country;
        this.aboutYou = aboutYou;
        this.mailingList = mailingList;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getGender() {
        return this.gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public String getAboutYou() {
        return this.aboutYou;
    }

    public void setAboutYou(String aboutYou) {
        this.aboutYou = aboutYou;
    }

    public boolean isMailingList() {
        return this.mailingList;
    }

    public void setMailingList(boolean mailingList) {
        this.mailingList = mailingList;
    }

    @Override
    public String toString() {
        return "Users{" + "id=" + id + ", name=" + name + ", gender=" + gender + ", country=" + country + ", aboutYou=" + aboutYou + ", mailingList=" + mailingList + '}';
    }

}
